name: WMS CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore ProductService
      run: dotnet restore ProductService/ProductService.csproj

    - name: Restore SupplyService
      run: dotnet restore SupplyService/SupplyService.csproj

    - name: Restore InventoryService
      run: dotnet restore InventoryService/InventoryService.csproj

    - name: Restore IntegrationGateway
      run: dotnet restore IntegrationGateway/IntegrationGateway.csproj

    - name: Restore Tests
      run: dotnet restore Tests/ProductService.Tests/ProductService.Tests.csproj

    - name: Format Check
      run: dotnet format --verify-no-changes

    - name: Build ProductService
      run: dotnet build ProductService/ProductService.csproj --no-restore

    - name: Build SupplyService
      run: dotnet build SupplyService/SupplyService.csproj --no-restore

    - name: Build InventoryService
      run: dotnet build InventoryService/InventoryService.csproj --no-restore

    - name: Build IntegrationGateway
      run: dotnet build IntegrationGateway/IntegrationGateway.csproj --no-restore

    - name: Run Tests
      run: dotnet test Tests/ProductService.Tests/ProductService.Tests.csproj

    - name: Docker Compose
      run: docker compose up -d