name: WMS CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Restore

      - name: Restore ProductService
        run: dotnet restore ProductService/ProductService.csproj

      - name: Restore SupplyService
        run: dotnet restore SupplyService/SupplyService.csproj

      - name: Restore InventoryService
        run: dotnet restore InventoryService/InventoryService.csproj

      - name: Restore IntegrationGateway
        run: dotnet restore IntegrationGateway/IntegrationGateway.csproj

      # Build

      - name: Build ProductService
        run: dotnet build ProductService/ProductService.csproj --configuration Release --no-restore

      - name: Build SupplyService
        run: dotnet build SupplyService/SupplyService.csproj --configuration Release --no-restore

      - name: Build InventoryService
        run: dotnet build InventoryService/InventoryService.csproj --configuration Release --no-restore

      - name: Build IntegrationGateway
        run: dotnet build IntegrationGateway/IntegrationGateway.csproj --configuration Release --no-restore

      # Docker

      - name: Build Product Docker Image
        run: docker build -t product-service ./ProductService

      - name: Build Supply Docker Image
        run: docker build -t supply-service ./SupplyService

      - name: Build Inventory Docker Image
        run: docker build -t inventory-service ./InventoryService

      - name: Build Gateway Docker Image
        run: docker build -t integration-gateway ./IntegrationGateway